package com.arthur.venue_api.Enum;

public enum TipoServicoEnum {
    // CATEGORIA: Entretenimento e Animação
    DJ,
    BANDA_AO_VIVO,
    MUSICO_SOLO,
    SHOW_DE_MAGICA,
    PALHACO,
    PERSONAGEM_FANTASIADO,
    ANIMADOR_INFANTIL,
    MONITOR_DE_BRINCADEIRAS,
    SHOW_DE_DANCA,
    PERFORMANCE_TEATRAL,

    // CATEGORIA: Serviços de Alimentação
    SELF_SERVICE,
    BUFFET_EXECUTIVO,
    COZINHA_A_VISTA,
    CHURRASQUEIRO_PROFISSIONAL,
    CONFEITEIRO,
    BARTENDER,
    GARCOM,
    ATENDIMENTO_MESA,
    SERVIÇO_QUITANDA,
    CAFE_DA_MANHA,

    // CATEGORIA: Estrutura e Logística
    MONTAGEM_DESMONTAGEM,
    LOCACAO_MOVEIS,
    LOCACAO_SOM_ILUMINACAO,
    TRANSPORTE_EQUIPAMENTOS,
    ESTACIONAMENTO_VALET,
    SEGURANCA,
    RECEPCIONISTA,

    // CATEGORIA: Decoração e Ambientação
    DECORADOR_EVENTOS,
    ARRANJOS_FLORAIS,
    ILUMINACAO_ESPECIAL,
    CENOGRAFIA,
    ALUGUEL_TAPETE,
    ARCO_BALOES,
    MESA_DOCES,
    PAINEL_FOTO,

    // CATEGORIA: Fotografia e Mídia
    FOTOGRAFO,
    FILMMAKER,
    FOTOBOTH,
    DRONE_COBERTURA,
    TRANSMISSAO_AO_VIVO,

    // CATEGORIA: Conforto e Acessibilidade
    AR_CONDICIONADO_PORTATIL,
    AQUECIMENTO_AMBIENTE,
    GERADOR_ENERGIA,
    BANHEIRO_QUIMICO,
    ACESSIBILIDADE_PCD,
    FRAUDAS_TROCAR,

    // CATEGORIA: Tecnologia
    WIFI_REFORCADO,
    TELA_PROJECAO,
    MICROFONIA,
    PODIUM,
    ESCRITORIO_VIRTUAL,

    // CATEGORIA: Especializados
    OFICINA_INFANTIL,
    BRINQUEDO_INFLAVEL,
    MESA_PING_PONG,
    SINUCA,
    MAQUINA_ALGODAO_DOCE,
    MAQUINA_PIPOCA
}
